# dplyr Library

The dplyr library is part of a family of R packages called the [tidyverse](https://www.tidyverse.org/). See the [dplyr documentation](https://dplyr.tidyverse.org/reference/index.html) for a summary of all the functions in this library. See also the [Data Transformations](https://r4ds.had.co.nz/transform.html) chapter of *R for Data Science* for more explanation and examples.

In [16]:
# You can ignore the warning about objects from other libraries being masked.
library(dplyr)

In [17]:
# The warn.conflicts=FALSE option supressess the warning about objects from other libraries being masked.
library(dplyr, warn.conflicts=FALSE)

<div class="admonition note" name="html-admonition">
<div class="title" style="background: lightblue; padding: 10px">Note</div>
<p>If you try to execute a dplyr function before loading the library, you will get an error messages stating that R could not find the function.</p>
</div>

## Example data
In this section, we will use the `ChickWeight` dataset which is built into R. Execute `?ChickWeight` in a code cell to view the documentation for this dataset.

In [ ]:
# Open the documentation for the built in ChickWeight dataset.
?ChickWeight

In [51]:
# Execute this code to restore ChickWieght to its original state.
remove(ChickWeight)

## mutate
Use the dplyr function `mutate()` to add or change columns. The basic syntax for this function is the following:

`mutate(DATA_FRAME, NEW_COLUMN = FORMULA)`

The mutate function outputs a **new** data frame which is generated by using the formula to create the data for a column called NEW_COLUMN in the specified DATA_FRAME.

In [52]:
# Convert the weight from grams to pounds.
# 1 gram is 0.00220462 pounds.
# mutate(ChickWeight, weight = weight * 0.00220462) # produces a large output

head(mutate(ChickWeight, weight = weight * 0.00220462), 3)
# We use the head() function to limit the output to the first three observations.

  weight     Time Chick Diet
1 0.09259404 0    1     1
2 0.11243562 2    1     1
3 0.13007258 4    1     1

In [41]:
# Notice that the ChickWeight data frame is unchanged.
head(ChickWeight,3)

  weight Time Chick Diet
1 42     0    1     1
2 51     2    1     1
3 59     4    1     1

<div class="admonition warning" name="html-admonition">
<div class="title" style="background: pink; padding: 10px">Warning</div>
    <p>If you want to keep the updated data frame that you produced with a dplyr function, then you must <b>store the output in a variable</b>.</p>
    <code>VARIABLE  &#60;- mutate(DATA_FRAME, NEW_COLUMN = FORMULA)</code>
</div>

In [47]:
# Store the output of mutate() in the ChickWeight data frame
# Assigning a value to a variable generates no output
ChickWeight <- mutate(ChickWeight, weight = weight * 0.00220462)

# Look at the first three observations of ChickWieght
head(ChickWeight,3)

  weight       Time Chick Diet
1 0.0002041347 0    1     1
2 0.0002478778 2    1     1
3 0.0002867606 4    1     1

### Compare to base R

In [50]:
# Restore ChickWeight to its original state
remove(ChickWeight)

# Use base R to convert the weight from grams to pounds and store the result.
ChickWeight$weight <- ChickWeight$weight * 0.00220462

# Look at the first three observations of ChickWieght
head(ChickWeight,3)

  weight     Time Chick Diet
1 0.09259404 0    1     1
2 0.11243562 2    1     1
3 0.13007258 4    1     1

## arrange
Use the dplyr `arrange()` to sort the observations of a data frame. The basic syntax for this function is the following:

`arrange(DATA_FRAME, COLUMN_NAME)`

The default is to sort the date frame so that the values of the specified column in *ascending* order. Put the COLUMN_NAME inside the the `desc()` function o sort in descending order.

`arrange(DATA_FRAME, desc(COLUMN_NAME))`

In [57]:
# Sort the ChickWeight data frame so that the values in the Time column are in ascending order.
arrange(ChickWeight, Time)

# This code allows us to look at the sorted data but does not save it anywhere.

    weight Time Chick Diet
1   42     0    1     1
2   40     0    2     1
3   43     0    3     1
4   42     0    4     1
5   41     0    5     1
6   41     0    6     1
7   41     0    7     1
8   42     0    8     1
9   42     0    9     1
10  41     0    10    1
11  43     0    11    1
12  41     0    12    1
13  41     0    13    1
14  41     0    14    1
15  41     0    15    1
16  41     0    16    1
17  42     0    17    1
18  39     0    18    1
19  43     0    19    1
20  41     0    20    1
21  40     0    21    2
22  41     0    22    2
23  43     0    23    2
24  42     0    24    2
25  40     0    25    2
26  42     0    26    2
27  39     0    27    2
28  39     0    28    2
29  39     0    29    2
30  42     0    30    2
⋮   ⋮      ⋮    ⋮     ⋮
549 117    21   20    1
550 331    21   21    2
551 167    21   22    2
552 175    21   23    2
553  74    21   24    2
554 265    21   25    2
555 251    21   26    2
556 192    21   27    2
557 233    21   28    2
558 309    21   29    2
559 150    21   30    2
560 256    21   31    3
561 305    21   32    3
562 147    21   33    3
563 341    21   34    3
564 373    21   35    3
565 220    21   36    3
566 178    21   37    3
567 290    21   38    3
568 272    21   39    3
569 321    21   40    3
570 204    21   41    4
571 281    21   42    4
572 200    21   43    4
573 196    21   45    4
574 238    21   46    4
575 205    21   47    4
576 322    21   48    4
577 237    21   49    4
578 264    21   50    4

<div class="admonition warning" name="html-admonition">
<div class="title" style="background: pink; padding: 10px">Warning</div>
    <p>The sorted data frame is the output; arrange does not change the original data frame. To replace the original data frame with the sorted one use</b>.</p>
    <code>DATA_FRAME  &#60;- arrange(DATA_FRAME, COLUMN_NAME)</code>
</div>

In [58]:
# Sort the ChickWeight data frame so that the values in the Time column are in descending order.
arrange(ChickWeight, desc(Time))

    weight Time Chick Diet
1   205    21   1     1
2   215    21   2     1
3   202    21   3     1
4   157    21   4     1
5   223    21   5     1
6   157    21   6     1
7   305    21   7     1
8    98    21   9     1
9   124    21   10    1
10  175    21   11    1
11  205    21   12    1
12   96    21   13    1
13  266    21   14    1
14  142    21   17    1
15  157    21   19    1
16  117    21   20    1
17  331    21   21    2
18  167    21   22    2
19  175    21   23    2
20   74    21   24    2
21  265    21   25    2
22  251    21   26    2
23  192    21   27    2
24  233    21   28    2
25  309    21   29    2
26  150    21   30    2
27  256    21   31    3
28  305    21   32    3
29  147    21   33    3
30  341    21   34    3
⋮   ⋮      ⋮    ⋮     ⋮
549 40     0    21    2
550 41     0    22    2
551 43     0    23    2
552 42     0    24    2
553 40     0    25    2
554 42     0    26    2
555 39     0    27    2
556 39     0    28    2
557 39     0    29    2
558 42     0    30    2
559 42     0    31    3
560 41     0    32    3
561 39     0    33    3
562 41     0    34    3
563 41     0    35    3
564 39     0    36    3
565 41     0    37    3
566 41     0    38    3
567 42     0    39    3
568 41     0    40    3
569 42     0    41    4
570 42     0    42    4
571 42     0    43    4
572 42     0    44    4
573 41     0    45    4
574 40     0    46    4
575 41     0    47    4
576 39     0    48    4
577 40     0    49    4
578 41     0    50    4

<div class="admonition note" name="html-admonition">
<div class="title" style="background: lightblue; padding: 10px">Note</div>
    <p><b>R cares about capitalizations</b>. The above code would not work if <code>Time</code> were replaced with <code>time</code>.</p>
</div>

### Sorting with respect to multiple columns
You can sort with respect to multiple columns by listing multiple column names in the arrange function:

`arrange(DATA_FRAME, COLUMN_NAME1,COLUMN_NAME2, COLUMN_NAME3, etc.)`

In [63]:
# Sort with respect to both Time and weight.
# Time values dominate the sort order.
arrange(ChickWeight, Time, weight)

    weight Time Chick Diet
1   39     0    18    1
2   39     0    27    2
3   39     0    28    2
4   39     0    29    2
5   39     0    33    3
6   39     0    36    3
7   39     0    48    4
8   40     0    2     1
9   40     0    21    2
10  40     0    25    2
11  40     0    46    4
12  40     0    49    4
13  41     0    5     1
14  41     0    6     1
15  41     0    7     1
16  41     0    10    1
17  41     0    12    1
18  41     0    13    1
19  41     0    14    1
20  41     0    15    1
21  41     0    16    1
22  41     0    20    1
23  41     0    22    2
24  41     0    32    3
25  41     0    34    3
26  41     0    35    3
27  41     0    37    3
28  41     0    38    3
29  41     0    40    3
30  41     0    45    4
⋮   ⋮      ⋮    ⋮     ⋮
549 192    21   27    2
550 196    21   45    4
551 200    21   43    4
552 202    21   3     1
553 204    21   41    4
554 205    21   1     1
555 205    21   12    1
556 205    21   47    4
557 215    21   2     1
558 220    21   36    3
559 223    21   5     1
560 233    21   28    2
561 237    21   49    4
562 238    21   46    4
563 251    21   26    2
564 256    21   31    3
565 264    21   50    4
566 265    21   25    2
567 266    21   14    1
568 272    21   39    3
569 281    21   42    4
570 290    21   38    3
571 305    21   7     1
572 305    21   32    3
573 309    21   29    2
574 321    21   40    3
575 322    21   48    4
576 331    21   21    2
577 341    21   34    3
578 373    21   35    3

<div class="admonition note" name="html-admonition">
<div class="title" style="background: lightblue; padding: 10px">Note</div>
    <p>The order of the column names in the <code>arrange()</code> function matters. The farther left a columns name is higher priority its values have in the sort order.</p>
</div>

In [64]:
# Sort with respect to both Time and weight.
# Weight values dominate the sort order.
arrange(ChickWeight, weight, Time)

    weight Time Chick Diet
1   35     2    18    1
2   39     0    18    1
3   39     0    27    2
4   39     0    28    2
5   39     0    29    2
6   39     0    33    3
7   39     0    36    3
8   39     0    48    4
9   39     2    3     1
10  40     0    2     1
11  40     0    21    2
12  40     0    25    2
13  40     0    46    4
14  40     0    49    4
15  41     0    5     1
16  41     0    6     1
17  41     0    7     1
18  41     0    10    1
19  41     0    12    1
20  41     0    13    1
21  41     0    14    1
22  41     0    15    1
23  41     0    16    1
24  41     0    20    1
25  41     0    22    2
26  41     0    32    3
27  41     0    34    3
28  41     0    35    3
29  41     0    37    3
30  41     0    38    3
⋮   ⋮      ⋮    ⋮     ⋮
549 264    20   50    4
550 264    21   50    4
551 265    21   25    2
552 266    21   14    1
553 269    20   42    4
554 272    21   39    3
555 275    16   21    2
556 279    20   29    2
557 280    20   38    3
558 281    21   42    4
559 287    16   35    3
560 288    20   7     1
561 290    21   38    3
562 291    20   32    3
563 294    18   34    3
564 295    20   40    3
565 303    20   48    4
566 305    21   7     1
567 305    21   32    3
568 307    18   21    2
569 309    21   29    2
570 318    20   21    2
571 321    21   40    3
572 322    21   48    4
573 327    20   34    3
574 331    21   21    2
575 332    18   35    3
576 341    21   34    3
577 361    20   35    3
578 373    21   35    3

## filter

## group_by and summarize